version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: m2test2
      MYSQL_DATABASE: m2test2
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: