version: '3'

networks:
  default:
    driver: bridge

services:

  app:
    build: .
    image: croissantshow
    ports:
      - 8173:8080
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: m2test2
      MYSQL_DATABASE: m2test2
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"      

volumes:
  my-datavolume: